
##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Pod
##
## Copyright (c) 2023 Robert Mollentze
## See LICENSE for details.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: example_temp_pods

## -----------------------------------------------------------------------------

environment:

  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.0.0"

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

  xyz_pod:
    path: ../../