##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_renaming_method_parameters: false
    avoid_web_libraries_in_flutter: true
    constant_identifier_names: false
    file_names: false
    non_constant_identifier_names: false
    omit_local_variable_types: true
    prefer_const_constructors_in_immutables: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    require_trailing_commas: true
    unnecessary_this: false
    camel_case_types: false
    library_private_types_in_public_api: false
    no_leading_underscores_for_local_identifiers: false
analyzer:
  exclude:
    - build/**
    # Exclude errors and warnings in generated files.
    #- '**/*.g.dart'
  errors:
    prefer_final_in_for_each: error
    unnecessary_new: error
    use_key_in_widget_constructors: error
    prefer_relative_imports: error
    unrelated_type_equality_checks: error
