##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Pod
##
## Copyright (c) 2023 Robert Mollentze
## See LICENSE for details.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_pod
description: XYZ Pod is a Flutter package designed to streamline and enhance state management in Flutter applications. It offers a suite of tools including `Pod`, `PodBuilder`, `PodListBuilder`, `MultiPodBuilder`, and `Pods` classes, each tailored to handle different aspects of state management with ease and flexibility.
version: 0.1.2
repository: https://github.com/robmllze/xyz_pod

## -----------------------------------------------------------------------------

environment:

  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1