# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#
# XYZ Utils
#
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

name: xyz_pod
description: A Provider/Riverpod layer for easier development
publish_to: none
version: 0.3.0
environment:
  sdk: '>=3.0.0-218.1.beta <4.0.0'
  flutter: ">=1.17.0"
dependency_overrides:
  xyz_utils:
    path: ../xyz_utils
dependencies:
  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git
      ref: master
  flutter_riverpod: ^2.3.1
  collection: ^1.17.1
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^2.0.0