##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Pod
##
## Copyright (c) 2023 Robert Mollentze
## See LICENSE for details.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_pod
description: This package is designed to simplify state management in Flutter applications and is well-suited for use with the Modular Services State Management (MSSM) pattern.
version: 0.16.1
repository: https://github.com/robmllze/xyz_pod

## -----------------------------------------------------------------------------

environment:

  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.0.0"

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1