##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Pod
##
## Copyright (c) 2023 Robert Mollentze
## See LICENSE for details.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_pod
description: XYZ Pod is a Flutter package designed to streamline and enhance state management in Flutter applications. It's based on Flutter's ValueNotifier.
version: 0.12.3
repository: https://github.com/robmllze/xyz_pod

## -----------------------------------------------------------------------------

environment:

  sdk: ">=3.0.0 <4.0.0"
  flutter: ">= 3.0.0"

## -----------------------------------------------------------------------------

dependencies:

  flutter:
    sdk: flutter

## -----------------------------------------------------------------------------

dev_dependencies:

  flutter_test:
    sdk: flutter
    
  flutter_lints: ^3.0.1